# Hugo site configuration
# Documentation: https://gohugo.io/getting-started/configuration/

title: TING JI
baseURL: 'https://jtecon.github.io/'

############################
## LANGUAGE
############################

defaultContentLanguage: en
hasCJKLanguage: false
defaultContentLanguageInSubdir: false
removePathAccents: true

enableGitInfo: false
summaryLength: 30
enableEmoji: true
enableRobotsTXT: true
ignoreFiles: [\.ipynb$, .ipynb_checkpoints$, \.Rmd$, \.Rmarkdown$, _cache$]
disableAliases: true
outputs:
  home:
    - HTML
    - RSS
    - Sitemap
  section:
    - HTML
    - RSS
imaging:
  resampleFilter: lanczos
  quality: 75
  anchor: smart
timeout: 600000
