# Site parameters

marketing:
  seo:
    description: 'Personal website of Ting Ji (纪珽), Associate Professor at CUFE. Research in international trade, economic geography, and the Chinese economy.'

header:
  navbar:
    enable: true
    align: c
    show_logo: true
    show_language: false
    show_day_night: false
    show_search: false
    highlight_active_link: true
